<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251226043406 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, action VARCHAR(100) NOT NULL, entity_type VARCHAR(100) NOT NULL, entity_id UUID DEFAULT NULL, old_values JSON DEFAULT NULL, new_values JSON DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D62F2858D17F50A6 ON audit_logs (uuid)');
        $this->addSql('CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id)');
        $this->addSql('CREATE INDEX idx_audit_user ON audit_logs (user_id)');
        $this->addSql('CREATE INDEX idx_audit_created ON audit_logs (created_at)');
        $this->addSql('CREATE TABLE bills_of_material (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, code VARCHAR(100) NOT NULL, version INT DEFAULT 1 NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, quantity_produced NUMERIC(15, 6) NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_product_id UUID NOT NULL, production_unit_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C99CA08BD17F50A6 ON bills_of_material (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C99CA08B77153098 ON bills_of_material (code)');
        $this->addSql('CREATE INDEX IDX_C99CA08B380E9C02 ON bills_of_material (finished_product_id)');
        $this->addSql('CREATE INDEX IDX_C99CA08BEDA8FDD0 ON bills_of_material (production_unit_id)');
        $this->addSql('CREATE TABLE bom_lines (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, quantity_required NUMERIC(15, 6) NOT NULL, waste_factor NUMERIC(5, 2) DEFAULT 0 NOT NULL, sequence INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, bom_id INT NOT NULL, component_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3CDE317D17F50A6 ON bom_lines (uuid)');
        $this->addSql('CREATE INDEX IDX_3CDE317BFD0DC92 ON bom_lines (bom_id)');
        $this->addSql('CREATE INDEX IDX_3CDE317E2ABAFFF ON bom_lines (component_id)');
        $this->addSql('CREATE UNIQUE INDEX bom_component_unique ON bom_lines (bom_id, component_id)');
        $this->addSql('CREATE TABLE companies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(255) NOT NULL, subdomain VARCHAR(100) NOT NULL, company_type VARCHAR(50) NOT NULL, plan_type VARCHAR(20) DEFAULT \'basic\' NOT NULL, status VARCHAR(20) DEFAULT \'active\' NOT NULL, settings JSON DEFAULT \'{}\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8244AA3AD17F50A6 ON companies (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8244AA3AC1D5962E ON companies (subdomain)');
        $this->addSql('CREATE TABLE customers (id UUID NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, customer_type VARCHAR(50) DEFAULT \'retail\' NOT NULL, contact_person VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, address TEXT DEFAULT NULL, credit_limit NUMERIC(15, 4) DEFAULT NULL, payment_terms VARCHAR(100) DEFAULT NULL, tax_id VARCHAR(100) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, attributes JSON DEFAULT \'{}\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_62534E2177153098 ON customers (code)');
        $this->addSql('CREATE TABLE global_users (id UUID NOT NULL, company_id UUID NOT NULL, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE measurement_units (id UUID NOT NULL, name VARCHAR(100) NOT NULL, symbol VARCHAR(20) NOT NULL, unit_type VARCHAR(50) NOT NULL, conversion_factor NUMERIC(15, 6) DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, base_unit_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F5AF83CFCCBBC969 ON measurement_units (base_unit_id)');
        $this->addSql('CREATE TABLE movement_types (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, effect VARCHAR(20) NOT NULL, requires_reference BOOLEAN DEFAULT false NOT NULL, is_system BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A48A5E25D17F50A6 ON movement_types (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A48A5E2577153098 ON movement_types (code)');
        $this->addSql('CREATE TABLE product_categories (id UUID NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, full_path VARCHAR(500) NOT NULL, description TEXT DEFAULT NULL, attributes JSON DEFAULT \'{}\' NOT NULL, sort_order INT DEFAULT 0 NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, parent_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A9941943727ACA70 ON product_categories (parent_id)');
        $this->addSql('CREATE TABLE production_orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, po_number VARCHAR(100) NOT NULL, status VARCHAR(50) DEFAULT \'planned\' NOT NULL, quantity_to_produce NUMERIC(15, 6) NOT NULL, quantity_produced NUMERIC(15, 6) DEFAULT 0 NOT NULL, start_date DATE DEFAULT NULL, completion_date DATE DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, bom_id INT NOT NULL, source_warehouse_id UUID DEFAULT NULL, destination_warehouse_id UUID DEFAULT NULL, created_by UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2A8F69B3D17F50A6 ON production_orders (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2A8F69B3EDAE42C5 ON production_orders (po_number)');
        $this->addSql('CREATE INDEX IDX_2A8F69B3BFD0DC92 ON production_orders (bom_id)');
        $this->addSql('CREATE INDEX IDX_2A8F69B3866A3066 ON production_orders (source_warehouse_id)');
        $this->addSql('CREATE INDEX IDX_2A8F69B3E1AE3711 ON production_orders (destination_warehouse_id)');
        $this->addSql('CREATE INDEX IDX_2A8F69B3DE12AB56 ON production_orders (created_by)');
        $this->addSql('CREATE TABLE products (id UUID NOT NULL, sku VARCHAR(100) NOT NULL, barcode VARCHAR(100) DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, product_type VARCHAR(50) NOT NULL, weight NUMERIC(10, 3) DEFAULT NULL, volume NUMERIC(10, 3) DEFAULT NULL, cost_price NUMERIC(15, 4) DEFAULT NULL, selling_price NUMERIC(15, 4) DEFAULT NULL, min_stock_level NUMERIC(15, 6) DEFAULT 0 NOT NULL, max_stock_level NUMERIC(15, 6) DEFAULT NULL, reorder_point NUMERIC(15, 6) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, attributes JSON DEFAULT \'{}\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id UUID DEFAULT NULL, unit_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B3BA5A5AF9038C4 ON products (sku)');
        $this->addSql('CREATE INDEX IDX_B3BA5A5A12469DE2 ON products (category_id)');
        $this->addSql('CREATE INDEX IDX_B3BA5A5AF8BD700D ON products (unit_id)');
        $this->addSql('CREATE TABLE purchase_order_lines (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, quantity_ordered NUMERIC(15, 6) NOT NULL, quantity_received NUMERIC(15, 6) DEFAULT 0 NOT NULL, unit_price NUMERIC(15, 4) NOT NULL, tax_rate NUMERIC(5, 2) DEFAULT 0 NOT NULL, expected_date DATE DEFAULT NULL, received_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, purchase_order_id INT NOT NULL, product_id UUID NOT NULL, warehouse_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B722E092D17F50A6 ON purchase_order_lines (uuid)');
        $this->addSql('CREATE INDEX IDX_B722E092A45D7E6A ON purchase_order_lines (purchase_order_id)');
        $this->addSql('CREATE INDEX IDX_B722E0924584665A ON purchase_order_lines (product_id)');
        $this->addSql('CREATE INDEX IDX_B722E0925080ECDE ON purchase_order_lines (warehouse_id)');
        $this->addSql('CREATE TABLE purchase_orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, po_number VARCHAR(100) NOT NULL, status VARCHAR(50) DEFAULT \'draft\' NOT NULL, order_date DATE NOT NULL, expected_delivery_date DATE DEFAULT NULL, delivery_date DATE DEFAULT NULL, total_amount NUMERIC(15, 4) DEFAULT 0 NOT NULL, tax_amount NUMERIC(15, 4) DEFAULT 0 NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, supplier_id UUID NOT NULL, approved_by UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3E40FFBBD17F50A6 ON purchase_orders (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3E40FFBBEDAE42C5 ON purchase_orders (po_number)');
        $this->addSql('CREATE INDEX IDX_3E40FFBB2ADD6D8C ON purchase_orders (supplier_id)');
        $this->addSql('CREATE INDEX IDX_3E40FFBB4EA3CB3D ON purchase_orders (approved_by)');
        $this->addSql('CREATE TABLE sales_order_lines (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, quantity_ordered NUMERIC(15, 6) NOT NULL, quantity_fulfilled NUMERIC(15, 6) DEFAULT 0 NOT NULL, unit_price NUMERIC(15, 4) NOT NULL, tax_rate NUMERIC(5, 2) DEFAULT 0 NOT NULL, reserved BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sales_order_id INT NOT NULL, product_id UUID NOT NULL, warehouse_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8894E9AFD17F50A6 ON sales_order_lines (uuid)');
        $this->addSql('CREATE INDEX IDX_8894E9AFC023F51C ON sales_order_lines (sales_order_id)');
        $this->addSql('CREATE INDEX IDX_8894E9AF4584665A ON sales_order_lines (product_id)');
        $this->addSql('CREATE INDEX IDX_8894E9AF5080ECDE ON sales_order_lines (warehouse_id)');
        $this->addSql('CREATE TABLE sales_orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, so_number VARCHAR(100) NOT NULL, status VARCHAR(50) DEFAULT \'draft\' NOT NULL, order_date DATE NOT NULL, due_date DATE DEFAULT NULL, total_amount NUMERIC(15, 4) DEFAULT 0 NOT NULL, tax_amount NUMERIC(15, 4) DEFAULT 0 NOT NULL, shipping_address TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, customer_id UUID NOT NULL, created_by UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C7DBAFE6D17F50A6 ON sales_orders (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C7DBAFE6D4237E00 ON sales_orders (so_number)');
        $this->addSql('CREATE INDEX IDX_C7DBAFE69395C3F3 ON sales_orders (customer_id)');
        $this->addSql('CREATE INDEX IDX_C7DBAFE6DE12AB56 ON sales_orders (created_by)');
        $this->addSql('CREATE TABLE stock_locations (id UUID NOT NULL, quantity_on_hand NUMERIC(15, 6) DEFAULT 0 NOT NULL, quantity_reserved NUMERIC(15, 6) DEFAULT 0 NOT NULL, quantity_ordered NUMERIC(15, 6) DEFAULT 0 NOT NULL, last_count_date DATE DEFAULT NULL, average_cost NUMERIC(15, 4) DEFAULT NULL, location_reference VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, warehouse_id UUID NOT NULL, product_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F7BAC525080ECDE ON stock_locations (warehouse_id)');
        $this->addSql('CREATE INDEX IDX_8F7BAC524584665A ON stock_locations (product_id)');
        $this->addSql('CREATE UNIQUE INDEX warehouse_product_unique ON stock_locations (warehouse_id, product_id)');
        $this->addSql('CREATE TABLE stock_movements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, quantity NUMERIC(15, 6) NOT NULL, unit_cost NUMERIC(15, 4) DEFAULT NULL, reference_id UUID DEFAULT NULL, reference_type VARCHAR(50) DEFAULT NULL, notes TEXT DEFAULT NULL, movement_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, movement_type_id INT NOT NULL, product_id UUID NOT NULL, from_warehouse_id UUID DEFAULT NULL, to_warehouse_id UUID DEFAULT NULL, user_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A0BE93C9D17F50A6 ON stock_movements (uuid)');
        $this->addSql('CREATE INDEX IDX_A0BE93C9EA4ED04A ON stock_movements (movement_type_id)');
        $this->addSql('CREATE INDEX IDX_A0BE93C94584665A ON stock_movements (product_id)');
        $this->addSql('CREATE INDEX IDX_A0BE93C96DC63638 ON stock_movements (from_warehouse_id)');
        $this->addSql('CREATE INDEX IDX_A0BE93C984154F02 ON stock_movements (to_warehouse_id)');
        $this->addSql('CREATE INDEX IDX_A0BE93C9A76ED395 ON stock_movements (user_id)');
        $this->addSql('CREATE INDEX idx_movement_date ON stock_movements (movement_date)');
        $this->addSql('CREATE INDEX idx_reference ON stock_movements (reference_type, reference_id)');
        $this->addSql('CREATE TABLE suppliers (id UUID NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, contact_person VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, address TEXT DEFAULT NULL, payment_terms VARCHAR(100) DEFAULT NULL, tax_id VARCHAR(100) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, attributes JSON DEFAULT \'{}\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AC28B95C77153098 ON suppliers (code)');
        $this->addSql('CREATE TABLE tenant_users (id UUID NOT NULL, global_user_id UUID NOT NULL, full_name VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL, permissions JSON DEFAULT \'{}\' NOT NULL, department VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE warehouses (id UUID NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, address TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, settings JSON DEFAULT \'{}\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AFE9C2B777153098 ON warehouses (code)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT FK_D62F2858A76ED395 FOREIGN KEY (user_id) REFERENCES tenant_users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bills_of_material ADD CONSTRAINT FK_C99CA08B380E9C02 FOREIGN KEY (finished_product_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bills_of_material ADD CONSTRAINT FK_C99CA08BEDA8FDD0 FOREIGN KEY (production_unit_id) REFERENCES measurement_units (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bom_lines ADD CONSTRAINT FK_3CDE317BFD0DC92 FOREIGN KEY (bom_id) REFERENCES bills_of_material (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bom_lines ADD CONSTRAINT FK_3CDE317E2ABAFFF FOREIGN KEY (component_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE measurement_units ADD CONSTRAINT FK_F5AF83CFCCBBC969 FOREIGN KEY (base_unit_id) REFERENCES measurement_units (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_categories ADD CONSTRAINT FK_A9941943727ACA70 FOREIGN KEY (parent_id) REFERENCES product_categories (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE production_orders ADD CONSTRAINT FK_2A8F69B3BFD0DC92 FOREIGN KEY (bom_id) REFERENCES bills_of_material (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE production_orders ADD CONSTRAINT FK_2A8F69B3866A3066 FOREIGN KEY (source_warehouse_id) REFERENCES warehouses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE production_orders ADD CONSTRAINT FK_2A8F69B3E1AE3711 FOREIGN KEY (destination_warehouse_id) REFERENCES warehouses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE production_orders ADD CONSTRAINT FK_2A8F69B3DE12AB56 FOREIGN KEY (created_by) REFERENCES tenant_users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A12469DE2 FOREIGN KEY (category_id) REFERENCES product_categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5AF8BD700D FOREIGN KEY (unit_id) REFERENCES measurement_units (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_order_lines ADD CONSTRAINT FK_B722E092A45D7E6A FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_order_lines ADD CONSTRAINT FK_B722E0924584665A FOREIGN KEY (product_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_order_lines ADD CONSTRAINT FK_B722E0925080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_orders ADD CONSTRAINT FK_3E40FFBB2ADD6D8C FOREIGN KEY (supplier_id) REFERENCES suppliers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_orders ADD CONSTRAINT FK_3E40FFBB4EA3CB3D FOREIGN KEY (approved_by) REFERENCES tenant_users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sales_order_lines ADD CONSTRAINT FK_8894E9AFC023F51C FOREIGN KEY (sales_order_id) REFERENCES sales_orders (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sales_order_lines ADD CONSTRAINT FK_8894E9AF4584665A FOREIGN KEY (product_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sales_order_lines ADD CONSTRAINT FK_8894E9AF5080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sales_orders ADD CONSTRAINT FK_C7DBAFE69395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sales_orders ADD CONSTRAINT FK_C7DBAFE6DE12AB56 FOREIGN KEY (created_by) REFERENCES tenant_users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_locations ADD CONSTRAINT FK_8F7BAC525080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_locations ADD CONSTRAINT FK_8F7BAC524584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_movements ADD CONSTRAINT FK_A0BE93C9EA4ED04A FOREIGN KEY (movement_type_id) REFERENCES movement_types (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_movements ADD CONSTRAINT FK_A0BE93C94584665A FOREIGN KEY (product_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_movements ADD CONSTRAINT FK_A0BE93C96DC63638 FOREIGN KEY (from_warehouse_id) REFERENCES warehouses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_movements ADD CONSTRAINT FK_A0BE93C984154F02 FOREIGN KEY (to_warehouse_id) REFERENCES warehouses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_movements ADD CONSTRAINT FK_A0BE93C9A76ED395 FOREIGN KEY (user_id) REFERENCES tenant_users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audit_logs DROP CONSTRAINT FK_D62F2858A76ED395');
        $this->addSql('ALTER TABLE bills_of_material DROP CONSTRAINT FK_C99CA08B380E9C02');
        $this->addSql('ALTER TABLE bills_of_material DROP CONSTRAINT FK_C99CA08BEDA8FDD0');
        $this->addSql('ALTER TABLE bom_lines DROP CONSTRAINT FK_3CDE317BFD0DC92');
        $this->addSql('ALTER TABLE bom_lines DROP CONSTRAINT FK_3CDE317E2ABAFFF');
        $this->addSql('ALTER TABLE measurement_units DROP CONSTRAINT FK_F5AF83CFCCBBC969');
        $this->addSql('ALTER TABLE product_categories DROP CONSTRAINT FK_A9941943727ACA70');
        $this->addSql('ALTER TABLE production_orders DROP CONSTRAINT FK_2A8F69B3BFD0DC92');
        $this->addSql('ALTER TABLE production_orders DROP CONSTRAINT FK_2A8F69B3866A3066');
        $this->addSql('ALTER TABLE production_orders DROP CONSTRAINT FK_2A8F69B3E1AE3711');
        $this->addSql('ALTER TABLE production_orders DROP CONSTRAINT FK_2A8F69B3DE12AB56');
        $this->addSql('ALTER TABLE products DROP CONSTRAINT FK_B3BA5A5A12469DE2');
        $this->addSql('ALTER TABLE products DROP CONSTRAINT FK_B3BA5A5AF8BD700D');
        $this->addSql('ALTER TABLE purchase_order_lines DROP CONSTRAINT FK_B722E092A45D7E6A');
        $this->addSql('ALTER TABLE purchase_order_lines DROP CONSTRAINT FK_B722E0924584665A');
        $this->addSql('ALTER TABLE purchase_order_lines DROP CONSTRAINT FK_B722E0925080ECDE');
        $this->addSql('ALTER TABLE purchase_orders DROP CONSTRAINT FK_3E40FFBB2ADD6D8C');
        $this->addSql('ALTER TABLE purchase_orders DROP CONSTRAINT FK_3E40FFBB4EA3CB3D');
        $this->addSql('ALTER TABLE sales_order_lines DROP CONSTRAINT FK_8894E9AFC023F51C');
        $this->addSql('ALTER TABLE sales_order_lines DROP CONSTRAINT FK_8894E9AF4584665A');
        $this->addSql('ALTER TABLE sales_order_lines DROP CONSTRAINT FK_8894E9AF5080ECDE');
        $this->addSql('ALTER TABLE sales_orders DROP CONSTRAINT FK_C7DBAFE69395C3F3');
        $this->addSql('ALTER TABLE sales_orders DROP CONSTRAINT FK_C7DBAFE6DE12AB56');
        $this->addSql('ALTER TABLE stock_locations DROP CONSTRAINT FK_8F7BAC525080ECDE');
        $this->addSql('ALTER TABLE stock_locations DROP CONSTRAINT FK_8F7BAC524584665A');
        $this->addSql('ALTER TABLE stock_movements DROP CONSTRAINT FK_A0BE93C9EA4ED04A');
        $this->addSql('ALTER TABLE stock_movements DROP CONSTRAINT FK_A0BE93C94584665A');
        $this->addSql('ALTER TABLE stock_movements DROP CONSTRAINT FK_A0BE93C96DC63638');
        $this->addSql('ALTER TABLE stock_movements DROP CONSTRAINT FK_A0BE93C984154F02');
        $this->addSql('ALTER TABLE stock_movements DROP CONSTRAINT FK_A0BE93C9A76ED395');
        $this->addSql('DROP TABLE audit_logs');
        $this->addSql('DROP TABLE bills_of_material');
        $this->addSql('DROP TABLE bom_lines');
        $this->addSql('DROP TABLE companies');
        $this->addSql('DROP TABLE customers');
        $this->addSql('DROP TABLE global_users');
        $this->addSql('DROP TABLE measurement_units');
        $this->addSql('DROP TABLE movement_types');
        $this->addSql('DROP TABLE product_categories');
        $this->addSql('DROP TABLE production_orders');
        $this->addSql('DROP TABLE products');
        $this->addSql('DROP TABLE purchase_order_lines');
        $this->addSql('DROP TABLE purchase_orders');
        $this->addSql('DROP TABLE sales_order_lines');
        $this->addSql('DROP TABLE sales_orders');
        $this->addSql('DROP TABLE stock_locations');
        $this->addSql('DROP TABLE stock_movements');
        $this->addSql('DROP TABLE suppliers');
        $this->addSql('DROP TABLE tenant_users');
        $this->addSql('DROP TABLE warehouses');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
